apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: smart-cart-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.65.200-192.168.65.210

---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: example
  namespace: metallb-system
